In [1]:
# Dependencies 
import requests
import json
import pandas as pd
import numpy as np
import csv
from pprint import pprint

# Google developer API key
from config import gkey

In [2]:
Zip_code = [33114, 33002, 33018, 33017, 33016, 33015, 33014, 33013, 33012, 33011, 33010, 33092, 
         33090, 33039, 33035, 33034, 33031, 33032, 33030, 33033, 33149, 33181, 33182, 33183, 
         33184, 33185, 33186, 33187, 33188, 33189, 33190, 33180, 33179, 33178, 33166, 33167, 
         33168, 33169, 33172, 33173, 33174, 33175, 33176, 33177, 33165, 33193, 33194, 33247, 
         33255, 33256, 33257, 33261, 33265, 33266, 33269, 33280, 33283, 33245, 33243, 33242, 
         33196, 33197, 33199, 33206, 33222, 33231, 33233, 33234, 33238, 33299, 33296, 33164, 
         33101, 33130, 33131, 33132, 3313, 33134, 33135, 33136, 33137, 33138, 33129, 33128, 
         33127, 33102, 33106, 33111, 33112, 33116, 33122, 33124, 33125, 33126, 33170, 33156, 
         33158, 33157, 33161, 33155, 33162, 33153, 33152, 33151, 33150, 33163, 33142, 33143, 
         33144, 33145, 33146, 33147, 33159, 33109, 33139, 33141, 33154, 33140, 33119, 33239, 
         33056, 33160, 33055, 33054]

In [3]:
data_to_load = "Zips_North.csv"
zipcode_data = pd.read_csv(data_to_load)
zipcode_data

       zip      latit      longi
0    33114  25.811133 -80.225947
1    33002  25.887981 -80.304334
2    33018  25.944540 -80.399265
3    33017  25.962450 -80.300777
4    33016  25.913921 -80.335236
5    33015  25.957270 -80.326881
6    33014  25.932358 -80.304597
7    33013  25.883274 -80.271159
8    33012  25.885521 -80.304597
9    33011  25.846162 -80.279327
10   33010  25.860603 -80.282306
11   33092  25.541400 -80.420000
12   33090  25.498027 -80.476438
13   33039  25.507442 -80.390916
14   33035  25.452276 -80.399265
15   33034  25.313386 -80.610489
16   33031  25.551932 -80.488267
17   33032  25.544639 -80.377000
18   33030  25.501675 -80.527176
19   33033  25.513534 -80.436742
20   33149  25.735200 -80.159604
21   33181  25.921788 -80.148441
22   33182  25.803980 -80.399265
23   33183  25.716462 -80.404831
24   33184  25.777802 -80.402048
25   33185  25.755288 -80.460464
26   33186  25.686793 -80.399265
27   33187  25.620842 -80.466026
28   33188  25.821400 -80.310000
29   33189  25.594824 -80.338021
..     ...        ...        ...
94   33170  25.626635 -80.554956
95   33156  25.679395 -80.287879
96   33158  25.660188 -80.307383
97   33157  25.629992 -80.338021
98   33161  25.912363 -80.181927
99   33155  25.757419 -80.315740
100  33162  25.947479 -80.181927
101  33153  25.886918 -80.193459
102  33152  25.814623 -80.317132
103  33151  25.853580 -80.209725
104  33150  25.870163 -80.207033
105  33163  25.971400 -80.150000
106  33142  25.834179 -80.237708
107  33143  25.720781 -80.293452
108  33144  25.783593 -80.312954
109  33145  25.774866 -80.226555
110  33146  25.742721 -80.271159
111  33147  25.869310 -80.237708
112  33159  25.791400 -80.190000
113  33109  25.777414 -80.134484
114  33139  25.804712 -80.148441
115  33141  25.874963 -80.148441
116  33154  25.908557 -80.126109
117  33140  25.839079 -80.137276
118  33119  25.805628 -80.132179
119  33239  25.811385 -80.139982
120  33056  25.980905 -80.243284
121  33160  25.956138 -80.137276
122  33055  25.965982 -80.282306
123  33054  25.934082 -80.243284

[124 rows x 3 columns]

In [4]:
# 3. Find the name and address of a gym in the zips. Needs to be gym as it is the type name provided by google
#    Hint: See https://developers.google.com/places/web-service/supported_types
namegymzip = []
addressgymzip = []
userratingszip = []
latgym = []
longym = []
pagetoken = []
gymsperzip = []
 
    #rewrite params dict
for i, row in zipcode_data.loc[:124,:].iterrows():
    params3 = {
        "location": f"{row['latit']},{row['longi']}",
        "types": "gym",
        "radius": 1250,
        "key": gkey
    }
    
    #print("params3...",params3)
    
    
# Build URL using the Google Maps API
    base_url3 = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    #print("Fitness Center near ZIP")

# Run request
    response = requests.get(base_url3, params3)
    gym_zips = response.json()
    # Print the JSON (pretty printed)
    #pprint(json.dumps(gym_zips, indent=4, sort_keys=True))
    #print(response.url)
    gymsperzip.append(len(gym_zips["results"]))
    # TODO: Add Wait for API Limiting?
    #if len(gym_zips["results"])>0:

        #print("Gym Zips Length...")
        #print(len(gym_zips["results"]))
        #for place in gym_zips["results"]:
            #print("Place...",place["name"])
            #try:
                #namegymzip.append(place["name"])
                #addressgymzip.append(place["vicinity"])
                #userratingszip.append(place["user_ratings_total"])
                #latgym.append(place["geometry"]["location"]["lat"])
                #longym.append(place["geometry"]["location"]["lng"])
            #except:
                #userratingszip.append("na")
                #latgym.append("na")
                #longym.append("na")
print(gymsperzip)      
# Print the JSON (pretty printed)
    #pprint(json.dumps(gym_zips, indent=4, sort_keys=True))

[3, 0, 0, 0, 5, 0, 5, 1, 0, 4, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 3, 18, 0, 0, 0, 0, 3, 0, 4, 0, 3, 14, 1, 0, 2, 1, 1, 1, 18, 4, 5, 2, 3, 0, 6, 0, 0, 3, 3, 13, 10, 0, 7, 4, 4, 5, 1, 15, 2, 3, 1, 1, 3, 17, 15, 6, 20, 19, 4, 20, 3, 1, 20, 14, 15, 0, 16, 3, 9, 20, 18, 3, 13, 20, 6, 4, 1, 20, 7, 0, 4, 6, 4, 0, 0, 1, 0, 10, 0, 1, 1, 2, 7, 2, 0, 5, 1, 0, 3, 15, 8, 1, 20, 20, 12, 0, 1, 1, 16, 7, 1, 11, 1, 2]

In [5]:
zipcode_dict2 = {
    "zip": Zip_code,
    "Gyms per Zip": gymsperzip
}

zipcode_data = pd.DataFrame(zipcode_dict2)
zipcode_data

       zip  Gyms per Zip
0    33114             3
1    33002             0
2    33018             0
3    33017             0
4    33016             5
5    33015             0
6    33014             5
7    33013             1
8    33012             0
9    33011             4
10   33010             1
11   33092             0
12   33090             0
13   33039             1
14   33035             0
15   33034             0
16   33031             0
17   33032             0
18   33030             0
19   33033             1
20   33149             3
21   33181            18
22   33182             0
23   33183             0
24   33184             0
25   33185             0
26   33186             3
27   33187             0
28   33188             4
29   33189             0
..     ...           ...
94   33170             0
95   33156             1
96   33158             0
97   33157            10
98   33161             0
99   33155             1
100  33162             1
101  33153             2
102  33152             7
103  33151             2
104  33150             0
105  33163             5
106  33142             1
107  33143             0
108  33144             3
109  33145            15
110  33146             8
111  33147             1
112  33159            20
113  33109            20
114  33139            12
115  33141             0
116  33154             1
117  33140             1
118  33119            16
119  33239             7
120  33056             1
121  33160            11
122  33055             1
123  33054             2

[124 rows x 2 columns]

In [6]:
zipcode_data.to_csv("Number_Gyms_North_Zip(r=1250).csv", encoding="utf-8", index=False)