In [1]:
# Dependencies 
import requests
import json
import pandas as pd
import numpy as np
import csv
from pprint import pprint

# Google developer API key
from config import gkey

In [2]:
Zip_code = [33114, 33002, 33018, 33017, 33016, 33015, 33014, 33013, 33012, 33011, 33010, 33092, 
         33090, 33039, 33035, 33034, 33031, 33032, 33030, 33033, 33149, 33181, 33182, 33183, 
         33184, 33185, 33186, 33187, 33188, 33189, 33190, 33180, 33179, 33178, 33166, 33167, 
         33168, 33169, 33172, 33173, 33174, 33175, 33176, 33177, 33165, 33193, 33194, 33247, 
         33255, 33256, 33257, 33261, 33265, 33266, 33269, 33280, 33283, 33245, 33243, 33242, 
         33196, 33197, 33199, 33206, 33222, 33231, 33233, 33234, 33238, 33299, 33296, 33164, 
         33101, 33130, 33131, 33132, 3313, 33134, 33135, 33136, 33137, 33138, 33129, 33128, 
         33127, 33102, 33106, 33111, 33112, 33116, 33122, 33124, 33125, 33126, 33170, 33156, 
         33158, 33157, 33161, 33155, 33162, 33153, 33152, 33151, 33150, 33163, 33142, 33143, 
         33144, 33145, 33146, 33147, 33159, 33109, 33139, 33141, 33154, 33140, 33119, 33239, 
         33056, 33160, 33055, 33054]

In [3]:
data_to_load = "Zips_East.csv"
zipcode_data = pd.read_csv(data_to_load)
zipcode_data

       zip      latit      longi
0    33114  25.789733 -80.202429
1    33002  25.866581 -80.280815
2    33018  25.923140 -80.375746
3    33017  25.941050 -80.277258
4    33016  25.892521 -80.311718
5    33015  25.935870 -80.303363
6    33014  25.910959 -80.281078
7    33013  25.861874 -80.247640
8    33012  25.864121 -80.281078
9    33011  25.824762 -80.255808
10   33010  25.839203 -80.258788
11   33092  25.520000 -80.396481
12   33090  25.476627 -80.452919
13   33039  25.486042 -80.367398
14   33035  25.430876 -80.375746
15   33034  25.291986 -80.586970
16   33031  25.530532 -80.464748
17   33032  25.523239 -80.353481
18   33030  25.480275 -80.503657
19   33033  25.492134 -80.413223
20   33149  25.713800 -80.136085
21   33181  25.900388 -80.124922
22   33182  25.782581 -80.375746
23   33183  25.695062 -80.381312
24   33184  25.756402 -80.378529
25   33185  25.733888 -80.436946
26   33186  25.665393 -80.375746
27   33187  25.599442 -80.442507
28   33188  25.800000 -80.286481
29   33189  25.573424 -80.314503
..     ...        ...        ...
94   33170  25.605235 -80.531437
95   33156  25.657995 -80.264361
96   33158  25.638788 -80.283864
97   33157  25.608592 -80.314503
98   33161  25.890963 -80.158408
99   33155  25.736019 -80.292221
100  33162  25.926079 -80.158408
101  33153  25.865518 -80.169940
102  33152  25.793223 -80.293614
103  33151  25.832180 -80.186206
104  33150  25.848763 -80.183514
105  33163  25.950000 -80.126481
106  33142  25.812779 -80.214189
107  33143  25.699381 -80.269933
108  33144  25.762193 -80.289435
109  33145  25.753466 -80.203036
110  33146  25.721321 -80.247640
111  33147  25.847910 -80.214189
112  33159  25.770000 -80.166481
113  33109  25.756014 -80.110966
114  33139  25.783312 -80.124922
115  33141  25.853563 -80.124922
116  33154  25.887158 -80.102591
117  33140  25.817680 -80.113757
118  33119  25.784228 -80.108660
119  33239  25.789985 -80.116464
120  33056  25.959505 -80.219765
121  33160  25.934738 -80.113757
122  33055  25.944582 -80.258788
123  33054  25.912682 -80.219765

[124 rows x 3 columns]

In [4]:
# 3. Find the name and address of a gym in the zips. Needs to be gym as it is the type name provided by google
#    Hint: See https://developers.google.com/places/web-service/supported_types
namegymzip = []
addressgymzip = []
userratingszip = []
latgym = []
longym = []
pagetoken = []
gymsperzip = []
 
    #rewrite params dict
for i, row in zipcode_data.loc[:124,:].iterrows():
    params3 = {
        "location": f"{row['latit']},{row['longi']}",
        "types": "gym",
        "radius": 1250,
        "key": gkey
    }
    
    #print("params3...",params3)
    
    
# Build URL using the Google Maps API
    base_url3 = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    #print("Fitness Center near ZIP")

# Run request
    response = requests.get(base_url3, params3)
    gym_zips = response.json()
    # Print the JSON (pretty printed)
    #pprint(json.dumps(gym_zips, indent=4, sort_keys=True))
    #print(response.url)
    gymsperzip.append(len(gym_zips["results"]))
    # TODO: Add Wait for API Limiting?
    #if len(gym_zips["results"])>0:

        #print("Gym Zips Length...")
        #print(len(gym_zips["results"]))
        #for place in gym_zips["results"]:
            #print("Place...",place["name"])
            #try:
                #namegymzip.append(place["name"])
                #addressgymzip.append(place["vicinity"])
                #userratingszip.append(place["user_ratings_total"])
                #latgym.append(place["geometry"]["location"]["lat"])
                #longym.append(place["geometry"]["location"]["lng"])
            #except:
                #userratingszip.append("na")
                #latgym.append("na")
                #longym.append("na")
print(gymsperzip)      
# Print the JSON (pretty printed)
    #pprint(json.dumps(gym_zips, indent=4, sort_keys=True))

[20, 1, 0, 0, 3, 7, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 4, 8, 7, 8, 2, 4, 0, 1, 0, 0, 0, 5, 0, 7, 0, 3, 1, 13, 2, 5, 2, 5, 1, 13, 8, 0, 2, 20, 0, 0, 7, 10, 3, 1, 1, 5, 9, 1, 20, 4, 0, 4, 15, 2, 0, 4, 1, 1, 7, 15, 18, 2, 20, 1, 19, 1, 18, 12, 8, 0, 0, 4, 13, 6, 1, 2, 1, 13, 0, 1, 18, 10, 3, 0, 0, 0, 0, 18, 2, 20, 4, 0, 17, 19, 1, 2, 2, 5, 11, 18, 1, 1, 0, 17, 10, 0, 4, 0, 1, 0, 5, 0, 1]

In [5]:
zipcode_dict2 = {
    "zip": Zip_code,
    "Gyms per Zip": gymsperzip
}

zipcode_data = pd.DataFrame(zipcode_dict2)
zipcode_data

       zip  Gyms per Zip
0    33114            20
1    33002             1
2    33018             0
3    33017             0
4    33016             3
5    33015             7
6    33014             0
7    33013             0
8    33012             1
9    33011             2
10   33010             2
11   33092             0
12   33090             2
13   33039             0
14   33035             0
15   33034             0
16   33031             1
17   33032             0
18   33030             0
19   33033             2
20   33149             0
21   33181             4
22   33182             8
23   33183             7
24   33184             8
25   33185             2
26   33186             4
27   33187             0
28   33188             1
29   33189             0
..     ...           ...
94   33170             0
95   33156             0
96   33158             0
97   33157             0
98   33161            18
99   33155             2
100  33162            20
101  33153             4
102  33152             0
103  33151            17
104  33150            19
105  33163             1
106  33142             2
107  33143             2
108  33144             5
109  33145            11
110  33146            18
111  33147             1
112  33159             1
113  33109             0
114  33139            17
115  33141            10
116  33154             0
117  33140             4
118  33119             0
119  33239             1
120  33056             0
121  33160             5
122  33055             0
123  33054             1

[124 rows x 2 columns]

In [6]:
zipcode_data.to_csv("Number_Gyms_East_Zip(r=1250).csv", encoding="utf-8", index=False)