In [1]:
# Dependencies 
import requests
import json
import pandas as pd
from census import Census


# Census API Key
from api_key import my_key
c = Census(my_key, year=2016)

In [2]:
# Run Census Search to retrieve data on all zip codes (2016 ACS5 Census)
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B02001_002E",
                          "B02001_003E", "B02001_004E", "B02001_005E",
                          "B02001_006E","B02001_008E", "B03001_003E", "B01002_001E", 
                          "B01002_002E","B01002_003E"), 
                          {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

In [3]:
census_pd.head()

,B01002_001E,B01002_002E,B01002_003E,B01003_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_008E,B03001_003E,B19013_001E,NAME,zip code tabulation area
0,45.0,41.6,48.1,17423.0,15974.0,256.0,5.0,703.0,24.0,184.0,1314.0,56714.0,ZCTA5 01001,01001
1,23.2,23.3,23.2,29970.0,23459.0,1711.0,140.0,3502.0,17.0,911.0,1870.0,48923.0,ZCTA5 01002,01002
2,19.9,19.9,19.9,11296.0,8698.0,660.0,30.0,1538.0,0.0,240.0,526.0,2499.0,ZCTA5 01003,01003
3,44.1,41.6,47.4,5228.0,5063.0,105.0,0.0,32.0,18.0,8.0,77.0,70568.0,ZCTA5 01005,01005
4,42.5,40.2,43.8,14888.0,13906.0,125.0,0.0,443.0,0.0,380.0,305.0,80502.0,ZCTA5 01007,01007

In [5]:
# Column Reordering
census_pd = census_pd.rename(columns={"B19013_001E": "Income" , 
                                      "B01003_001E": "Population", 
                                      "B02001_002E": "Population White",
                                      "B02001_003E": "Population Black",
                                      "B02001_004E": "Population American Indian", 
                                      "B02001_005E": "Population Asian",
                                      "B02001_006E": "Population Hawaiian",
                                      "B02001_008E": "Population 2 or more Races", 
                                      "B03001_003E": "Population Hispanic", 
                                      "B01002_001E": "Age", 
                                      "B01002_002E": "Median Male Age",
                                      "B01002_003E": "Median Female Age",
                                      "NAME": "Name", 
                                      "zip code tabulation area": "Zipcode"})

    
                      

# Final DataFrame
census_pd = census_pd[["Zipcode","Income",  "Population","Population White",  
                                    "Population White",
                                    "Population Black",
                                    "Population American Indian", 
                                    "Population Asian",
                                    "Population Hawaiian",
                                    "Population 2 or more Races", 
                                    "Population Hispanic", 
                                    "Age", 
                                    "Median Male Age",
                                    "Median Female Age"
                                   ]]

# Visualize
print(len(census_pd))
census_pd.head(50)

33120

,Zipcode,Income,Population,Population White,Population White,Population Black,Population American Indian,Population Asian,Population Hawaiian,Population 2 or more Races,Population Hispanic,Age,Median Male Age,Median Female Age
0,01001,56714.0,17423.0,15974.0,15974.0,256.0,5.0,703.0,24.0,184.0,1314.0,45.0,41.6,48.1
1,01002,48923.0,29970.0,23459.0,23459.0,1711.0,140.0,3502.0,17.0,911.0,1870.0,23.2,23.3,23.2
2,01003,2499.0,11296.0,8698.0,8698.0,660.0,30.0,1538.0,0.0,240.0,526.0,19.9,19.9,19.9
3,01005,70568.0,5228.0,5063.0,5063.0,105.0,0.0,32.0,18.0,8.0,77.0,44.1,41.6,47.4
4,01007,80502.0,14888.0,13906.0,13906.0,125.0,0.0,443.0,0.0,380.0,305.0,42.5,40.2,43.8
5,01008,67250.0,1194.0,1182.0,1182.0,0.0,0.0,7.0,0.0,5.0,4.0,48.5,49.4,46.9
6,01009,-666666666.0,237.0,237.0,237.0,0.0,0.0,0.0,0.0,0.0,0.0,62.2,61.5,66.6
7,01010,83273.0,3718.0,3703.0,3703.0,9.0,0.0,6.0,0.0,0.0,43.0,46.6,46.3,47.2
8,01011,74722.0,1523.0,1462.0,1462.0,15.0,0.0,11.0,0.0,17.0,51.0,41.0,39.9,43.0
9,01012,60417.0,528.0,520.0,520.0,0.0,0.0,0.0,2.0,6.0,11.0,50.5,50.7,48.0
10,01013,40876.0,22943.0,19344.0,19344.0,808.0,28.0,524.0,0.0,320.0,5753.0,35.0,33.3,36.8
11,01020,57851.0,30629.0,27211.0,27211.0,957.0,58.0,385.0,0.0,811.0,4484.0,44.5,43.5,45.7
12,01022,44701.0,2528.0,1848.0,1848.0,414.0,0.0,45.0,0.0,164.0,269.0,41.1,31.4,51.7
13,01026,50924.0,1018.0,974.0,974.0,33.0,0.0,0.0,0.0,11.0,10.0,51.2,51.3,51.2
14,01027,61217.0,17872.0,16675.0,16675.0,326.0,3.0,240.0,0.0,376.0,1178.0,45.1,43.4,46.7
15,01028,83003.0,16063.0,14485.0,14485.0,981.0,26.0,328.0,0.0,204.0,457.0,46.0,46.0,46.1
16,01029,54375.0,760.0,746.0,746.0,7.0,0.0,0.0,0.0,7.0,4.0,47.9,49.6,47.2
17,01030,64874.0,11278.0,10824.0,10824.0,195.0,6.0,209.0,0.0,35.0,708.0,44.9,43.9,46.0
18,01031,39327.0,1192.0,1161.0,1161.0,8.0,0.0,0.0,0.0,23.0,9.0,43.2,37.5,46.1
19,01032,73750.0,590.0,586.0,586.0,0.0,0.0,4.0,0.0,0.0,10.0,49.3,51.3,43.0
20,01033,86951.0,6310.0,6172.0,6172.0,0.0,0.0,18.0,0.0,60.0,436.0,45.5,46.4,45.0
21,01034,82159.0,2323.0,2278.0,2278.0,2.0,2.0,7.0,0.0,29.0,40.0,46.6,46.4,46.8
22,01035,62634.0,5338.0,5001.0,5001.0,121.0,20.0,119.0,0.0,43.0,239.0,46.3,45.9,47.0
23,01036,80375.0,5190.0,5143.0,5143.0,10.0,0.0,26.0,0.0,11.0,106.0,48.7,49.1,48.4
24,01037,80417.0,755.0,692.0,692.0,12.0,0.0,0.0,0.0,20.0,73.0,50.3,30.6,53.8
25,01038,65887.0,2853.0,2787.0,2787.0,21.0,0.0,36.0,0.0,9.0,1.0,50.7,49.8,51.4
26,01039,74107.0,1194.0,1170.0,1170.0,6.0,0.0,0.0,0.0,8.0,30.0,54.0,51.3,54.9
27,01040,38829.0,40280.0,33779.0,33779.0,1780.0,228.0,747.0,26.0,874.0,20130.0,34.4,31.7,36.9
28,01050,72386.0,2343.0,2192.0,2192.0,95.0,4.0,0.0,4.0,44.0,8.0,45.7,43.0,47.7
29,01053,66528.0,1697.0,1579.0,1579.0,62.0,0.0,15.0,0.0,20.0,76.0,49.8,46.0,57.5
30,01054,86771.0,1972.0,1900.0,1900.0,15.0,3.0,22.0,0.0,32.0,27.0,48.0,46.3,50.1
31,01056,64537.0,21352.0,20079.0,20079.0,251.0,23.0,290.0,18.0,198.0,1409.0,44.2,43.1,46.3
32,01057,74439.0,8773.0,8471.0,8471.0,26.0,0.0,79.0,0.0,168.0,123.0,45.5,45.8,45.1
33,01060,56128.0,15407.0,13290.0,13290.0,548.0,23.0,813.0,0.0,457.0,1398.0,35.0,37.4,32.8
34,01062,73913.0,10867.0,9520.0,9520.0,153.0,6.0,676.0,0.0,354.0,878.0,43.8,41.7,45.6
35,01063,-666666666.0,563.0,387.0,387.0,23.0,0.0,107.0,0.0,40.0,46.0,20.3,20.4,20.3
36,01066,-666666666.0,12.0,12.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,-666666666.0,-666666666.0,-666666666.0
37,01068,85052.0,1825.0,1788.0,1788.0,4.0,11.0,5.0,0.0,17.0,45.0,45.0,45.2,44.7
38,01069,57994.0,8753.0,8569.0,8569.0,125.0,0.0,6.0,0.0,53.0,146.0,44.0,42.0,47.0
39,01070,55208.0,562.0,518.0,518.0,3.0,1.0,14.0,0.0,20.0,14.0,52.7,50.6,53.4
40,01071,70938.0,1271.0,1220.0,1220.0,11.0,5.0,8.0,0.0,27.0,11.0,47.9,49.3,47.5
41,01072,75658.0,1542.0,1434.0,1434.0,13.0,8.0,9.0,0.0,72.0,70.0,46.8,45.5,48.4
42,01073,90318.0,6081.0,6004.0,6004.0,0.0,0.0,62.0,0.0,15.0,24.0,48.4,45.6,49.1
43,01074,-666666666.0,228.0,228.0,228.0,0.0,0.0,0.0,0.0,0.0,0.0,35.2,35.6,33.6
44,01075,61821.0,17770.0,15875.0,15875.0,562.0,22.0,668.0,0.0,534.0,939.0,40.8,44.7,37.2
45,01077,76576.0,9650.0,9255.0,9255.0,1.0,0.0,158.0,0.0,236.0,15.0,45.7,46.2,45.3
46,01079,31778.0,811.0,811.0,811.0,0.0,0.0,0.0,0.0,0.0,32.0,42.8,43.3,42.4
47,01080,51023.0,2452.0,2194.0,2194.0,53.0,0.0,0.0,0.0,205.0,127.0,33.5,30.5,38.7
48,01081,51182.0,1823.0,1805.0,1805.0,2.0,0.0,0.0,0.0,12.0,42.0,43.5,44.1,43.2
49,01082,52178.0,10612.0,10105.0,10105.0,72.0,11.0,50.0,39.0,311.0,437.0,43.2,40.8,45.0

In [5]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_pd.to_csv("census_data.csv", encoding="utf-8", index=False)

In [6]:
#To select rows whose column value is in list 
Zip_code = [33114, 33002, 33018, 33017, 33016, 33015, 33014, 33013, 33012, 33011, 33010, 33092, 
         33090, 33039, 33035, 33034, 33031, 33032, 33030, 33033, 33149, 33181, 33182, 33183, 
         33184, 33185, 33186, 33187, 33188, 33189, 33190, 33180, 33179, 33178, 33166, 33167, 
         33168, 33169, 33172, 33173, 33174, 33175, 33176, 33177, 33165, 33193, 33194, 33247, 
         33255, 33256, 33257, 33261, 33265, 33266, 33269, 33280, 33283, 33245, 33243, 33242, 
         33196, 33197, 33199, 33206, 33222, 33231, 33233, 33234, 33238, 33299, 33296, 33164, 
         33101, 33130, 33131, 33132, 33133, 33134, 33135, 33136, 33137, 33138, 33129, 33128, 
         33127, 33102, 33106, 33111, 33112, 33116, 33122, 33124, 33125, 33126, 33170, 33156, 
         33158, 33157, 33161, 33155, 33162, 33153, 33152, 33151, 33150, 33163, 33142, 33143, 
         33144, 33145, 33146, 33147, 33159, 33109, 33139, 33141, 33154, 33140, 33119, 33239, 
         33056, 33160, 33055, 33054]
census_pd.Zipcode.isin(Zip_code)

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
33090    False
33091    False
33092    False
33093    False
33094    False
33095    False
33096    False
33097    False
33098    False
33099    False
33100    False
33101    False
33102    False
33103    False
33104    False
33105    False
33106    False
33107    False
33108    False
33109    False
33110    False
33111    False
33112    False
33113    False
33114    False
33115    False
33116    False
33117    False
33118    False
33119    False
Name: Zipcode, Length: 33120, dtype: bool

In [9]:
census_pd= census_pd[census_pd.Zipcode.isin(Zip_code)]
census_pd

Empty DataFrame
Columns: [Zipcode, Income, Population, Population White, Population White, Population Black, Population American Indian, Population Asian, Population Hawaiian, Population 2 or more Races, Population Hispanic, Age, Median Male Age, Median Female Age]
Index: []

In [11]:
census_pd.dtypes

Zipcode                        object
Income                        float64
Population                    float64
Population White              float64
Population White              float64
Population Black              float64
Population American Indian    float64
Population Asian              float64
Population Hawaiian           float64
Population 2 or more Races    float64
Population Hispanic           float64
Age                           float64
Median Male Age               float64
Median Female Age             float64
dtype: object

In [27]:

census_pd = census_pd.astype({"Zipcode": int})

Empty DataFrame
Columns: [Zipcode, Income, Population, Population White, Population White, Population Black, Population American Indian, Population Asian, Population Hawaiian, Population 2 or more Races, Population Hispanic, Age, Median Male Age, Median Female Age]
Index: []

In [24]:
census_pd.dtypes

Zipcode                         int32
Income                        float64
Population                    float64
Population White              float64
Population White              float64
Population Black              float64
Population American Indian    float64
Population Asian              float64
Population Hawaiian           float64
Population 2 or more Races    float64
Population Hispanic           float64
Age                           float64
Median Male Age               float64
Median Female Age             float64
dtype: object

In [30]:
census_pd[census_pd.Zipcode.isin(Zip_code)]

Empty DataFrame
Columns: [Zipcode, Income, Population, Population White, Population White, Population Black, Population American Indian, Population Asian, Population Hawaiian, Population 2 or more Races, Population Hispanic, Age, Median Male Age, Median Female Age]
Index: []